services:
  mongodb:
    image: mongo:7.0
    container_name: nexus-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexus-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/restaurant_db
      - PORT=3000
      - HOSTNAME=0.0.0.0
    depends_on:
      - mongodb

volumes:
  mongodb_data:
